CREATE TABLE attachments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    media_type         VARCHAR(255),
    post_id            VARCHAR(255)                            NOT NULL,
    media_source_url   TEXT,
    media_image_height INTEGER,
    media_image_src    TEXT,
    media_image_width  INTEGER,
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

CREATE TABLE posts
(
    graph_api_id VARCHAR(255) NOT NULL,
    message      TEXT,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (graph_api_id)
);

CREATE TABLE sub_attachments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type               VARCHAR(255),
    url                TEXT,
    attachment_id      BIGINT                                  NOT NULL,
    media_source_url   TEXT,
    media_image_height INTEGER,
    media_image_src    TEXT,
    media_image_width  INTEGER,
    target_id          VARCHAR(255),
    target_url         TEXT,
    CONSTRAINT pk_sub_attachments PRIMARY KEY (id)
);

ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (graph_api_id);

ALTER TABLE sub_attachments
    ADD CONSTRAINT FK_SUB_ATTACHMENTS_ON_ATTACHMENT FOREIGN KEY (attachment_id) REFERENCES attachments (id);