spring:
  application:
    name: training-service
  config:
    import: configserver:${CONFIG_SERVER:http://localhost:8888}


server:
  port: 8082 # Port de l'application pour éviter les conflits locaux



