server:
  port: 8888
spring:
  application:
    name:
      config-service

encrypt:
  key-store:
    location: classpath:config-keystore.p12
    password: ${CONFIG_SERVICE_KEYSTORE_PASS}
    alias: config-key
    type: 'PKCS12'



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}