spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_URI:https://github.com/bbsebb/temp-configuration.git}
          clone-on-start: true
          skipSslValidation: true