spring:
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SERVER_URI}
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0 # Définir à 100% (1.0) pour capturer toutes les requêtes


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"




