services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    #    ports:
    #      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - observability-network

  tempo:
    image: grafana/tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./.tempo/tempo-data:/tmp/tempo
      - ./tempo/tempo.yml:/etc/tempo.yaml:ro
    #    ports:
    #      - "3200:3200"  # Tempo
    #      - "9411:9411"  # Zipkin
    networks:
      - observability-network

  loki:
    image: grafana/loki:main
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    #    ports:
    #      - "3100:3100"
    volumes:
      - loki_data:/loki
    networks:
      - observability-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    #    ports:
    #      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - observability-network

networks:
  observability-network:
    driver: bridge

volumes:
  prometheus_data:
  loki_data:
  grafana_data: