version: '3.8'

services:
  postgres-kc:
    image: postgres:17.4
    container_name: kc-db-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-devuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword}
      POSTGRES_DB: kc-db
    volumes:
      - postgres_data_kc:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-kc:5432/kc-db
      KC_DB_USERNAME: ${POSTGRES_USER:-devuser}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-devpassword}
    ports:
      - "8079:8080"
    depends_on:
      - postgres-kc
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./import-realm.sh:/opt/keycloak/bin/import-realm.sh
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data_kc:
  keycloak_data: