services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-staging.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key:ro
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - backend-network
      - observability-network
      - keycloak-network
