services:
  postgres-kc: # Nom du service
    image: postgres:17.4 # Image officielle PostgreSQL (version: 15)
    container_name: kc-db-container-dev # Nom du conteneur
    restart: always # Redémarre le conteneur automatiquement si nécessaire
    environment:
      POSTGRES_USER: devuser # Nom d'utilisateur pour PostgreSQL
      POSTGRES_PASSWORD: devpassword # Mot de passe de l'utilisateur
      POSTGRES_DB: kc-db # Nom de la base de données initiale
    volumes:
      - postgres_data_kc_dev:/var/lib/postgresql/data # Volume Docker pour persister les données

  keycloak-dev:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kc-db-container-dev:5432/kc-db
      KC_DB_USERNAME: devuser
      KC_DB_PASSWORD: devpassword
    ports:
      - "8079:8080"
    depends_on:
      - postgres-kc


volumes:
  postgres_data_kc_dev: