-- Création de la table pour gérer les salles

CREATE TABLE hall (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant auto-généré
                      name VARCHAR(255) NOT NULL,                             -- @NotBlank
                      street VARCHAR(255) NOT NULL,                          -- @NotBlank dans Address
                      city VARCHAR(255) NOT NULL,                            -- @NotBlank dans Address
                      postal_code VARCHAR(5) NOT NULL,                       -- @Pattern(regexp = "\\d{5}")
                      CHECK (postal_code ~ '^\d{5}$'),                       -- Contrainte de format sur le code postal
                      country VARCHAR(255) NOT NULL                          -- @NotBlank dans Address
);

-- Création de la table des équipes
CREATE TABLE team (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Identifiant auto-généré
                      gender VARCHAR(10) NOT NULL,                             -- Enum Gender (F, M, N), @NotNull
                      category VARCHAR(10) NOT NULL,                           -- Enum Category (U11, U13, etc.), @NotNull
                      team_number INT NOT NULL,                                -- @NotNull
                      CONSTRAINT unique_team UNIQUE (gender, category, team_number) -- Contrainte de combinaison unique
);

-- Création de la table des sessions d'entraînement
CREATE TABLE training_session (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- Identifiant auto-généré
                                  day_of_week VARCHAR(10) NOT NULL,                           -- Enum DayOfWeek (lundi, mardi, etc.), @NotBlank
                                  start_time TIME NOT NULL,                                   -- TimeSlot start_time
                                  end_time TIME NOT NULL,                                     -- TimeSlot end_time
                                  hall_id BIGINT REFERENCES hall(id) ON DELETE SET NULL,      -- Relation avec Hall (nullable)
                                  team_id BIGINT REFERENCES team(id) ON DELETE CASCADE        -- Relation avec Team (cascade suppression)
);

-- Création de la table des entraîneurs
CREATE TABLE coach (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- Identifiant auto-généré
                       name VARCHAR(255) NOT NULL,                                 -- @NotBlank
                       surname VARCHAR(255) NOT NULL,                              -- @NotBlank
                       email VARCHAR(255) NOT NULL UNIQUE,                         -- @Email avec contrainte d'unicité
                       phone VARCHAR(15) NOT NULL,                                 -- @Pattern(regexp = "\\+?[0-9]{10,15}")
                       CHECK (phone ~ '^\+?[0-9]{10,15}$')                        -- Validation pour tester le format du téléphone
);

-- Création de la table liant les entraîneurs et les équipes via des rôles
CREATE TABLE role_coach (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- Identifiant auto-généré
                            coach_id BIGINT NOT NULL REFERENCES coach(id) ON DELETE CASCADE, -- Relation avec Coach
                            team_id BIGINT NOT NULL REFERENCES team(id) ON DELETE CASCADE,  -- Relation avec Team
                            role VARCHAR(20) NOT NULL
);